### ISSUE TITLE
Can the code handle app process death while the user is in a web browser in front?

### ISSUE THREAD

**Issue by kmansoft** [openid/AppAuth-Android#104]
I should preface this by stating that I'm only looking at this library as sample code (for the "modernized" OAUTH flow), and have no plans to actually use it.

It's not apparent to me if the sample app and the library would be able to handle this scenario:

1 - User initiates approval flow (the initial stage where "this app would like to know your email, name, ...")

2 - The app makes a `PendingIntent` for `TokenActivity` and the library stores it in `PendingIntentStore`

3 - Chome (or some other browser) comes up in front of the app, user starts interacting with it

4 - Android kills the app which is now in background (memory pressure, whatever). `PendingIntentStore` and everything in it is gone

5 - User finally presses "Agree", the browser fires the "custom scheme intent"

6 - Android creates a new process for the app  and launches `RedirectUriReceiverActivity`

And now:

7 - `PendingIntentStore` will not have the original intent and `getOriginalRequest` inside `RedirectUriReceiverActivity` will return null and the subsequent logic for handling the authorization code will fail.

That is, unless I'm missing something  and `MainActivity` (which was in front when Chrome with the authorization screen popped up) or something else is going to re-create the original pending intent and register it in `PendingIntentStore` before `RedirectUriReceiverActivity` needs to use it.

Another interesting case is the user changing the device's orientation while on the approval screen in the web browser. Then Android may destroy and re-create `MainActivity` and that, from looking at the code, will launch a whole new "flow" for approval.

**Comment by graynote** [comment]
I also have concern about above scenario that current library cannot handle. That scenario is one of the reason why we have used WebView that we cannot use in the future anymore. Google play service sign-in does not have this problem because it uses dialog not full screen activity. But we need to use browser based oauth. 

Chrome looks like having a hidden customtabs feature that makes calling app foreground. But because we need to  support a device does not have a customtabs browser, it is not enough.

**Comment by iainmcgin** [comment]
The risk you highlight is real, and one we are aware of but we have not yet had any reports of this happening in practice yet. Everything we currently store in PendingIntentStore can be persisted to survive process death, but so far in the library we have avoided making decisions for the client app on where or how data should be persisted. We intend to revisit the implementation of PendingIntentStore to support customizable persistence with a sensible default.

The rotation bug you mention in the demo app is easily fixed but is the responsibility of the client app, not the library.

I'll reiterate that we are happy to accept pull requests to resolve problems such as these. We don't want to leave any excuse for continued use of WebView, due to its dire security properties, so please do continue to highlight scenarios where you feel some bug or behavioral aspect of AppAuth would push you back towards WebView.

**Comment by iainmcgin** [comment]
This is now fixed by #109 - we are no longer using a static map to store information.
