### ISSUE TITLE
Communication problems between AuthorizationManagementActivity and RedirectUriReceiverActivity are caused by an Android 14 task stack issue.

### ISSUE THREAD

**Issue by akoueikjc** [openid/AppAuth-Android#1061]
Checklist:

- [x]  I am using the latest release
- [x]  I searched for [existing GitHub issues](https://github.com/openid/AppAuth-Android/issues)
- [x]  I read the [documentation](https://github.com/openid/AppAuth-Android/blob/master/README.md)
- [x]  I verified the client configuration matches the information in the identity provider (or I am using dynamic client registration)
- [x]  I am either using a custom URI scheme or https with [App Links](https://developer.android.com/training/app-links) for client redirect.
- [x]  I can reproduce the issue in the demo app (optional)
- [ ] 

Configuration

- Version: 0.11.1
- Integration: native Java
- Identity provider: Google

### Issue Description
My Problem is only on Android 14 devices. Google Pixel 7 Pro API 34.
I have Activity A and B. 
Activity B has it own taskAffinity, and im launching the AuthRequest from Activity B and finishing im getting `No stored state - unable to handle response` warn from `AuthorizationManagementActivity`.
and its not redirecting the activity B but opening it own Task instance.

I've attempted to use `AuthorizationManagementActivity` and `RedirectUriReceiverActivity` with the same custom taskAffinity. It was unsuccessful. (DID NOT WORK)

**Comment by LaxmikantMahamuni** [comment]
@akoueikjc  How did you checked the AuthorizationManagementActivity's own Task instance?

I am suspecting that this issue is on Google Pixel 4A (Vanilla OS) and Android 14. 
Issue at My end -> 
AuthorizationManagementActivity ptints "No stored state - unable to handle response" for first time and then intermittently when app is killed and launched again to follow the path to launch AuthorizationManagementActivity. As a result when the "No stored state - unable to handle response" message printed then app freezes. Latter if I back press then app is working as smooth as it was working before. 
So, I am suspecting that app freezes means it has AuthorizationManagementActivity's Task instance which causing this issue.

Note: On Android-11, App works properly to land AuthorizationManagementActivity and browser for authentication every-time even if the app is killed or not. 

I am new to use this AppAuth-Android lib.  
Your reply might land me on correct path to find the solution for my issue, if I am wrong about above findings. Thanks!

**Comment by akoueikjc** [comment]
Please note that this issue has nothing to do with AppAuth-Android library.

I already gave my answer here https://github.com/openid/AppAuth-Android/issues/977#issuecomment-2129326556 

do there is a way to bypass Samsung Android 14 bug on the activity Result
