### ISSUE TITLE
Authorization response/error are null

### ISSUE THREAD

**Issue by vineus** [openid/AppAuth-Android#118]
Hey there,

I followed the integration guide, the google tutorial and the demo app, but I can't get the authorization working... 

I perform the authorization request, perform the auth on a chrome tab, the intent is fired and I get back in the app (I can read from logcat that the oauth "code" is present in the custom app URI called to start the RedirectUriReceiverActivity).

But I keep getting nothing from `AuthorizationResponse.fromIntent` and the following error is raised:

`E/AppAuth: Response received for unknown request with state null`

from `RedirectUriReceiverActivity`

I tried both 0.2.0 and 0.3.0 version

Any idea what could go wrong ?

Thanks a lot for your help!

**Comment by vineus** [comment]
Ok, answering my own question, reading the source of `RedirectUriReceiverActivity` solved my issue, the AppAuth code adds a `state` parameter to the query and this wasn't passed back to my custom redirect endpoint.

Sorry for the bug tracker pollution :-p

**Comment by iainmcgin** [comment]
No worries Vince, OAuth2 from mobile devices can be pretty confusing. I'll try to start putting together an FAQ for these kinds of issues soon.

**Comment by nrgarach** [comment]
Hi Vineus, 

I am getting the same error that you saw initially.  "E/AppAuth: Response received for unknown request with state null". Can you please elaborate on how did you read "state" parameter?

I am using app-auth library on android. Sign up page takes me to form to enter details and once I am done, back of login should take me to my login page instead when I tap on back to login it does nothing and gives me above error. This works fine on browser but this issue exists only on android device.

**Comment by vineus** [comment]
Hey @nrgarach 

I didn't read the "state" parameter, it contains data used by the library. My mistake was that I had a custom redirect endpoint that was taking only the oauth2 parameters (such as `token_type` or `code`) and was stripping away any extra.

You can read here: https://github.com/openid/AppAuth-Android/blob/59fdc91b235dabd6f9766aea6683b761e9a48673/library/java/net/openid/appauth/AuthorizationResponse.java#L230 that the AppAuth-Android lib uses an extra `state` query parameter, which has nothing to do with oauth itself but stores current state.

So you have to make sure you don't strip this AppAuth-Android set parameters if you build oauth reidrect URL yourself (basically just pass all incoming parameters to the redirected URL and don't try to select them manually).

Hope this is clear enough (re-reading this I don't really think so :-) ).

**Comment by iainmcgin** [comment]
`state` actually is a standard (optional) OAuth2 parameter; it is intended for use to correlate responses to requests. The string is opaque to the server, and should not be modified by it.

@nrgarach - as @vineus says, we read this state parameter out of the parameters sent to the redirect URI once the authorization request completes. We automatically generate a state value in the requests, unless specifically overridden by the client, and the error you are referring to means that a response was received that does not contain the expected state value. In this case, with `null`, no state parameter was included in the response.

What identity provider are you trying to integrate with? Does it correctly implement the OAuth2 specification?

**Comment by nrgarach** [comment]
Thanks @vineus  and @iainmcgin. 

I am trying to integrate ARTIKCloud - https://developer.artik.cloud/documentation/introduction/authentication.html. The problem is when I go to sign up from my mobile app, it asks me to fill in details and then takes me to a page where it says thanks for registering with hyperlink "Back to login". On clicking this hyperlink "Back to login" I get the error - "E/AppAuth: Response received for unknown request with state null". I want to go back to login page when I click this. When using ARTIKCloud with webviews, I intercepted url to find out if I had redirect url with orgin=signup parameter and if yes then I try to load the login page and it worked. Any ideas, how can I handle same here?

**Comment by iainmcgin** [comment]
I managed to modify the demo application to work with Artik Cloud, so there's no issue with the library. There are a few issues with Artik Cloud itself, however:

- It requires the use of a client_secret to get an authorization code. They don't recommend doing this from a mobile application, which means that the secret carries some privileges that make it unsuitable for mobile apps (this isn't always the case).

- Transmission of the client secret is done via an Authorization header on the token endpoint, however it is done in a [strange way](https://developer.artik.cloud/documentation/introduction/authentication.html#sending-clientid-and-clientsecret), combining the client ID and client secret (decoded from hex to bytes) and then Base64 encoding the result.

- The redirect URI can only be an https URL, which means you'll need to use an app link or an intermediary page to capture the response. See [my demo app](https://github.com/iainmcgin/AppAuth-Demo) for an example of this.

Anyway, it's possible from the info you included above that you're not using the right authorization endpoint - I don't see "back to login" when I send authorization requests to `https://accounts.artik.com/authorize`.

**Comment by nrgarach** [comment]
Thank you for trying this out @iainmcgin . I am able to send the authorization request successfully and obtain the access token to make API calls using this library. The issue is when instead of user loggin in user does signup on the https://accounts.artik.cloud/authorize page. It asks for details and after sign up button is hit it takes to page with "Back to login". This "Back to login" should take back to https://accounts.artik.cloud/authorize page which would allow user to login, I am not able to do this last part(Going from "Back to login" to login page) I want help specific to handle this part. Thanks.

**Comment by svachmic** [comment]
Hi @nrgarach a year and something later - we're facing the same issue as you did. Any pointers on how you went around solving this? Thanks!

**Comment by LucasFebatis** [comment]
Missing an excerpt explaining the `createResponseHandlingIntent` in the readme

From what I understood here with me it was returning null for

```
AuthorizationResponse resp = AuthorizationResponse.fromIntent(data);
AuthorizationException ex = AuthorizationException.fromIntent(data);
```

Because of him
