### ISSUE TITLE
dynamic configurations

### ISSUE THREAD

**Issue by emezias** [openid/AppAuth-Android#129]
It's not obvious from the sample app and documentation how to use this library when the login/authorization endpoints are dynamic, coming into the app from the server at runtime rather than set into xml at build time.

In one permutation, the app displays a list of sign-in options. Once selected, I open the url from the list with an add on json parameter. A successful login uses deep links to get back to the app. 

Can I use the AppAuth-Android library without any hard-coded, build time, configuration xml files?

Thanks in advance for your assistance.

**Comment by iainmcgin** [comment]
No build time configuration is needed for AppAuth other than associating a redirect URI to capture authorization responses. The demo app uses XML config to store client IDs and URIs just to make it easier to set up and run, so it's not very representative of a client app that uses a more dynamic set of authorization services.

Given an authorization endpoint URI, token endpoint URI and client ID from your server, 
It should be straightforward to construct an `AuthorizationServiceConfiguration` and `Authorization  Request` from these and start the authorization flow. Something like:

```
AuthorizationServiceConfiguration config = 
    new AuthorizationServiceConfiguration(authEndpointUri, tokenEndpointUri);

AuthorizationRequest request = 
    new AuthorizationRequest.Builder(
        config,
        clientId,
        ResponseTypeValues.CODE,
        myRedirectUri)
    .setScopes("a", "b")
    .build();

mAuthorizationService.performAuthorizationRequest(request, CompletionActivity.getIntent());
```

**Comment by emezias** [comment]
Hi Iain,
Thanks so much for the quick response. I found the codelab and made some
progress. Can I use a
regex in that manifest placeholder? I want the URI to match something like:

https://app-intent filter url/[hard to guess
value]/kurogo_login/return_native?[QUERY_PARAMS]

AppAuth is so much cleaner than my custom tabs implementation. It's really
a great solution.

Thanks and regards!

On Nov 30, 2016 6:52 PM, "Iain McGinniss" <notifications@github.com> wrote:

No build time configuration is needed for AppAuth other than associating a
redirect URI to capture authorization responses. The demo app uses XML
config to store client IDs and URIs just to make it easier to set up and
run, so it's not very representative of a client app that uses a more
dynamic set of authorization services.

Given an authorization endpoint URI, token endpoint URI and client ID from
your server,
It should be straightforward to construct an AuthorizationServiceConfigurat
ion and Authorization Request from these and start the authorization flow.
Something like:

AuthorizationServiceConfiguration config =
    new AuthorizationServiceConfiguration(authEndpointUri, tokenEndpointUri);

AuthorizationRequest request =
    new AuthorizationRequest.Builder(
        config,
        clientId,
        ResponseTypeValues.CODE,
        myRedirectUri)
    .setScopes("a", "b")
    .build();

mAuthorizationService.performAuthorizationRequest(request,
CompletionActivity.getIntent());

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/openid/AppAuth-Android/issues/129#issuecomment-264034829>,
or mute the thread

**Comment by iainmcgin** [comment]
Using the manifest placeholder probably doesn't suit your use case, as it's only really intended to change the scheme. However, you can completely ignore it by overriding the manifest merge and define your own intent-filter with a path pattern:

```xml
<activity 
    android:name="net.openid.appauth.RedirectUriReceiverActivity" 
    android:exported="true"
    tools:node="replace">
  <intent-filter>
    <action android:name="android.intent.action.VIEW"/>
    <category android:name="android.intent.category.DEFAULT"/>
    <category android:name="android.intent.category.BROWSABLE"/>
    <data 
        android:scheme="https"
        android:host="www.mydomain.com"
        android:pathPattern="/.*/kurogo_login/return_native.*"
        />
  </intent-filter>
</activity>
```

The [`tools:node="replace"`](https://developer.android.com/studio/build/manifest-merge.html#node_markers) directive will prevent the existing declaration from the library from being merged. The docs for the kinds of patterns you can use in pathPattern is [here](https://developer.android.com/reference/android/os/PatternMatcher.html#PATTERN_SIMPLE_GLOB).

Ideally, you should also use "android:autoVerify=true" and a digital asset link to "claim" the URL for security reasons. You can read more on this [here](https://developer.android.com/training/app-links/index.html).

**Comment by emezias** [comment]
Hi again,

Here is my unusual situation. The team here has already implemented logic
for login. The server side is completing login and then the redirect back
to the app may or may not be secured with digital assets. At present, we
are into Chrome Intents (javascript intents,
https://developer.chrome.com/multidevice/android/intents#example) to
redirect back to the app. The server side is not strictly OAuth 2.0. We
work with a lot of SAML.

A Custom Tab redirect back to the app based on the URL in an intent filter
is not working right now - with or without the app auth library.
The onNavigationEvent is not firing with custom tab creation and the
redirect following login should hit the app intent filter and does not seem
to do anything.

Here are 3 points where your feedback would be most w


   1. When compiling the appauth library, gradle won't build without a
   placeholder entry. Gradle often overrides the Android manifest. What should
   I put in the gradle, can I give it an empty string?
   android.defaultConfig.manifestPlaceholders = [ 'appAuthRedirectScheme':
   'com.modolabs.kand28://kgologin_return']

   2. When creating an AuthRequest, I do not have the explicit URL to build
   a redirect Uri for the request. I have the scheme - it's that intent filter
   we talked about yesterday. How do I set the redirect Uri?


*hostname from intent filter/[hard to guess
   value]/kurogo_login/return_native?[QUERY_PARAMS] *
   3. Can I use an explicit intent for the Pending intent in the call to
   performAuthorizationRequest instead of creating an action in my app? I
   tried testing that but my redirects from the Chrome Tab following sign
   in are not opening the app (as mentioned previously).

   4. The QUERY_PARAMS are to provide me with the next steps for the app,
   login success/failure logic comes back in the form of these parameters. The
   complete URL that is opened by the app after login can spell out the next
   pages to visit, deliver the token(s). This sidesteps the appauth library.
   The structure creates consistency and also allows flexibility with login
   authorities. Is it cool to use the appauth just to manage the Chrome Tabs?

Thanks very much!
Best regards,
Beth

------------------------------------

Elizabeth Mezias

Senior Software Engineer

Modo Labs, Inc.

http://www.modolabs.com/

*Making Mobile Awesome for Everyone*

**Comment by iainmcgin** [comment]
1. If you're not using a custom redirect scheme, I would just use an empty string for that placeholder in addition to the "tools:replace" directive I explained above.

2. If the server side is not actually OAuth2, then the value of the redirect URI in the authorization request maybe doesn't matter. The value provided to AuthorizationRequest ultimately becomes the URL parameter "redirect_uri"; see [here](https://github.com/openid/AppAuth-Android/blob/master/library/java/net/openid/appauth/AuthorizationRequest.java#L930). So, if your server isn't even paying attention to that, you can probably just supply some dummy URI.

3. If the custom tab isn't redirecting to your app, I don't think this is anything to do with the pending intent that you are supply as part of performAuthorizationRequest. First, I would test that if you create a test page with an <a href="..."> link with something that should match your app, that clicking on this opens your app. If this doesn't work, there's some problem with your intent-filter declaration. You can test it directly using adb as follows:

```
adb shell am start -W -a android.intent.action.VIEW -c android.intent.category.DEFAULT -d MY_URL
```

Try that for a few different values of MY_URL that you expect to match your filter and see if it gives the option to launch your app.

One other thing to aware of is that Chrome will typically only launch an app from an _explicit user action_, like a click on a link or button that results in the redirect. Javascript triggered or chained redirects won't always be given the opportunity to launch an app. I don't know exactly what behavior to expect here if you're using intent:// links to get back to the app.

4. It definitely sounds like what you're doing isn't strictly OAuth2, so AppAuth likely isn't a great fit for you. It should certainly be possible to just extract the core pieces into a separate library in order to manage launching a tab and capturing a response. We (Google) have considered building this but there has not been a need to provide this as a standalone library.

It shouldn't be too hard to extract this from AppAuth: the code from [performAuthorizationRequest](https://github.com/openid/AppAuth-Android/blob/master/library/java/net/openid/appauth/AuthorizationService.java#L201) to launch the tab is pretty simple, and the [AuthorizationManagementActivity](https://github.com/openid/AppAuth-Android/blob/master/library/java/net/openid/appauth/AuthorizationManagementActivity.java) and [RedirectUriReceiverActivity](https://github.com/openid/AppAuth-Android/blob/master/library/java/net/openid/appauth/RedirectUriReceiverActivity.java) can likely be simplified for your purposes - maybe you don't care about verifying a state parameter, or attempting to directly decode the response. Extracting those two classes and single method should be sufficient to give you the core of AppAuth that you actually want, without all the additional OAuth2 specific helper classes.

**Comment by emezias** [comment]
Thanks very much! This is helpful.
