### ISSUE TITLE
Getting the oauth response in RedirectUriReceiverActivity

### ISSUE THREAD

**Issue by jonathanraes** [openid/AppAuth-Android#164]
Hi,

Im creating an app that logs into my elixir backend server using oauth.
I can do the request, get redirected and I can see that I'm logged in and receive my token from the server.
However, I never get redirected back to the app and when I click back I always end up in handleAuthorizationCanceled(). 
I read that I need to set up my "scheme" in the manifest or build settings but I dont understand at all what that is.. 
Im talking about this part:
```xml
<data android:scheme="https"
              android:host="www.example.com"
              android:path="/oauth2redirect"/>
```
Should I put my app's url here? It currently runs locally on my laptop so I acces it via the emulator with http://10.0.2.2:4000
What should I put in here? Nothing I try seems to work.

Oh and I saw people saying put in com.googleusercontent.apps.<MY_ID_ADDED_HERE>, but my app is a github app, not google.
Thanks in advance

**Comment by iainmcgin** [comment]
GitHub does not support redirect to a custom scheme redirect URI, they only support redirect to https URIs last I checked. Custom scheme URIs look like `com.your.app://oauth2redirect`, where the `com.your.app` part is the custom scheme.

I have a demo of GitHub integration here:

https://github.com/iainmcgin/AppAuth-Demo

*Please read the caveats about security carefully*. GitHub also requires the use of a static client secret, which is not advisable for mobile apps. I give some advice on that demo repository page as to how to integrate with GitHub securely, but it is not trivial and requires backend work.

**Comment by jonathanraes** [comment]
Thanks for your reply.
Im planning on supporting a range of OAuth providers for my app, but I see it will be more work than i hoped on.
Ill stick to email:password auth for now. Later ill come back and look at using my backend as an OAuth connect authorization service as is mentioned in that demo repo.

**Comment by nycodes9** [comment]
what if some OAuth providers provide custom schemes as redirect like Microsoft (where redirect endpoint is urn:ietf:wg:oauth:2.0:oob) the scheme doesn't work

**Comment by nycodes9** [comment]
`manifestPlaceholders = [
                'appAuthRedirectScheme': 'none'
        ]`

And why is manifestPlaceholder a mandatory requirement since we have an alternative of option of implementing 
`RedirectUriReceiverActivity`

I read your [Why this is bad?](https://github.com/iainmcgin/AppAuth-Demo) and also the [rfc - Using Custom URI Schemes for Redirection](https://tools.ietf.org/html/draft-wdenniss-oauth-native-apps-02#page-7) it seems that 

> urn:ietf:wg:oauth:2.0:oob is compliant 

yet parsing that either by appAuthRedirectScheme or RedirectUriReceiverActivity fails.
Kindly suggest

**Comment by iainmcgin** [comment]
`urn:ietf:wg:oauth:2.0:oob` cannot be registered on Android or iOS devices, as it is intended to be used within an embedded web browser. Having multiple apps register this standard redirect URI would result in the user being prompted to choose between multiple apps to handle the redirect - a bad user experience, and a security vulnerability too without PKCE. Google and other IDPs are likely to discontinue oob in the near future due to this.

As for manifestPlaceholders, we were trying to make it easy to specify the custom scheme for redirect purely through build configuration. You can replace the `<activity>` declaration for RedirectUriReceiverActivity provided by the library, by using `tools:node="replace"` if you don't want to use a custom scheme:

```xml
<activity android:name="net.openid.appauth.RedirectUriReceiverActivity"
          tools:node="replace">
            <intent-filter>
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>

                <!-- whatever redirect capture you want here -->

            </intent-filter>
        </activity>
```

See also: https://developers.google.com/identity/protocols/OAuth2InstalledApp#choosingredirecturi

**Comment by nycodes9** [comment]
Thanks
