### ISSUE TITLE
Support "claims" OpenID Connect auth request parameter

### ISSUE THREAD

**Issue by iainmcgin** [openid/AppAuth-Android#20]
[OpenID Connect Core 1.0, Section 5.5](https://openid.net/specs/openid-connect-core-1_0.html#ClaimsParameter), `claims` parameter:

> OPTIONAL. This parameter is used to request that specific Claims be returned. The value is a JSON object listing the requested Claims.
> 
> An example Claims request is as follows:
> 
> ``` json
> {
>   "userinfo":
>   {
>       "given_name": {"essential": true},
>       "nickname": null,
>       "email": {"essential": true},
>       "email_verified": {"essential": true},
>       "picture": null,
>       "http://example.info/claims/groups": null
>   },
>   "id_token":
>   {
>       "auth_time": {"essential": true},
>       "acr": {"values": ["urn:mace:incommon:iap:silver"] }
>   }
> }
> ```

**Comment by Abdelsattar** [comment]
any WIP for this enhancement and how we can currently send claims?

**Comment by agologan** [comment]
@Abdelsattar added support for passing in `claims` and `claims_locales` in `v0.10.0`.
Since claims is a structured object you'll have to create and pass in a `JSONObject` to make use of it.

_You can also use `additionalParameters` to pass in parameters which are not yet supported by the lib._
Let me know if you run into any issues.

**Comment by Abdelsattar** [comment]
Thanks, @agologan for the updates, yes Currently I'm using additionalParameters to send it and will use claim when refactor
