### ISSUE TITLE
How do we set the client secret in the Token Endpoint Request ?

### ISSUE THREAD

**Issue by LaluGanesh** [openid/AppAuth-Android#234]
in token endpoint request **
**"Authorization code exchange failed invalid_client**" error will occur.
i am using in my app **Client ID:Client** Secret this format. confusion is where i put the Client Secret value?
anyone can help?

**Comment by iainmcgin** [comment]
See this section of the README:

https://github.com/openid/AppAuth-Android#utilizing-client-secrets-dangerous

**Comment by eric-jswang** [comment]
Due to  legacy issue, I need to use client_secret_basic, and am  trying to apply to AppAuth-demo-app the method mentioned In the README link https://github.com/openid/AppAuth-Android#utilizing-client-secrets-dangerous, ie.,

      authService.performTokenRequest(req, clientAuth, callback);

However, in current AppAuth-demo-app, the clientAuthentication is now manged by StateManager. It looks that the StateManager will never create ClientSecretBasic for static clients.

By creating a new ClientSecretBasic outside control of StateManager, I am sure that the latest AppAuth-demo-app is able to internally successfully get access-token from authorization code, but its UI eventually comes up with,

    "Not Authorized, Authorization Code exchange failed : null"

Would you kindly guide the way to the possible fix ? Thanks very much !

**Comment by MKevin3** [comment]
I really need to be able to do this as well. Has anyone come up with sample code on how to use the dangerous client side secret mode?
