### ISSUE TITLE
Not redirected back to app on second login

### ISSUE THREAD

**Issue by amosli-cinco** [openid/AppAuth-Android#241]
Hi,
I'm trying to implement a sign in with instagram on my app.
When I first press login, the browser is opened and I'm requested to authorize the app. I do so and RedirectUriReceiverActivity is called and everything works fine.
The second time I do this (or rather when the user has already authorized the app) I'm not getting redirected back to the app.

Any ideas?

**Comment by iainmcgin** [comment]
Is the second authorization request being handled automatically, without user interaction? Chrome typically requires user interaction (e.g. clicking on a button on link) to trigger custom scheme or app links, otherwise the redirect request is rejected.

So, if Instagram is automatically redirecting because the user has already consented, you will need to handle this by using an "interstitial" page to capture the redirect, and have the user click a button to transfer the result to the app. I do this in my [own demo]() of AppAuth that interacts with GitHub, which has the same issue. The redirect handling page is [here](https://appauth.demo-app.io/oauth2redirect), if you look at the source you'll see that all it does is extract the request parameters and transfer them to a custom scheme.

**Comment by amosli-cinco** [comment]
You are correct, it does happen when there is no user interaction.
Thing is I've been using this library for a couple of months now (on another app) and I could have sworn it used to work - now it doesn't work on my other app as well. 
I'll try implementing your workaround. Thanks.
