### ISSUE TITLE
Log out not clearing the session 

### ISSUE THREAD

**Issue by prashanthd** [openid/AppAuth-Android#244]
Hi Team,

After log out when I try to log in it is not asking credentials. I  am manually clearing the cookies from browser to enter new credentials. But my requirement is after logging out it should ask credentials for logging in. is there any way I can implement?

**Comment by iainmcgin** [comment]
To revoke the session and associated tokens within the browser, the identity provider you are integrating with must provide a [token revocation](https://tools.ietf.org/html/rfc7009) or [session management](https://openid.net/specs/openid-connect-session-1_0.html#RPLogout) endpoint. As these are not broadly supported, AppAuth does not provide any helper methods to interact with such endpoints; you will have to investigate this further yourself.

**Comment by Onkarn92** [comment]
Hi iainmcgin,

I'm using AppAuth **v0.6.1**. Is there any way (or public method) to clear cookies & cache of custom tab using AppAuth? In my case, I want to clear `authorization_code` which is active only for one hour. So, within that one hour, I can't log in as another user because of `authorization_code`. Can you please help me with that?

**Comment by Onkarn92** [comment]
@iainmcgin It would be great If you could help me :)

**Comment by iainmcgin** [comment]
I'm not sure I understand your question; in OAuth2 `authorization_code` is intended to be a single use value that is exchanged for other tokens (typically a refresh token). Your issues doesn't sound AppAuth related - if you're reporting an AppAuth bug, please open another issue rather than reusing this one.

**Comment by Onkarn92** [comment]
Thanks for your valuable time @iainmcgin, I just want to confirm that; Is there any public method to clear the cookies & cache of chrome custom tab instance that I can use from my 'Activity'?

**Comment by Onkarn92** [comment]
@iainmcgin Let me explain my scenario first. Please refer this [image](https://i.imgur.com/lZXZ6HA.png) containing OAuth 2.0 data flow. 

1. Authorization Request will be triggered from an app.
2. _Authorization Endpoint_ will authenticate user credentials.
3. `authorization_code` will be provided from _Authorization Endpoint_ after successful login (Please refer step 3 in the image). This `authorization_code` will be **active for one hour** (In my case).
4. An app will pass `authorization_code` to _Token Endpoint_, Which will provide `access_token` or `refresh_token`. 

So, Issue is user can't log in with another user credentials within that one hour (Because `authorization_code` is active). The browser will automatically redirect to **Token Endpoint** and it'll generate new `access_token` for the same user.

However, I just want to clear this active `authorization_code` after successful login. So, The browser will redirect to _Authorization Endpoint_ (Login screen) instead of _Token Endpoint_

I think this `authorization_code` will get saved in browser cookies/cache. If I clear cookies/cache, everything will work as expected.

Any help will be appreciated :)

Cheers,
Onkar

**Comment by Onkarn92** [comment]
@iainmcgin could you please help me? I'm stuck with this problem.

**Comment by WilliamDenniss** [comment]
@Onkarn92 likely the session at the authorization server is still active and the authorization server is issuing a *new* `authorization_code` (the `authorization_code` is not being saved). What you're asking for sounds like you need multi-user support at the authorization server, like what Google's OAuth server offers, or at least the opportunity for the user to sign-in with a different account during authorization.

This is an authorization server issue, so you'll need to bring this up with them.  AppAuth is working as intended here.

**Comment by Onkarn92** [comment]
@WilliamDenniss Thanks, I appreciate your help :) Now, I got a clear idea about this problem. This is the server issue, not the client one.
