### ISSUE TITLE
Slow implementation

### ISSUE THREAD

**Issue by icedice** [openid/AppAuth-Android#328]
I'm not sure if I'm doing something wrong, but i have a button which triggers my login flow. in my login flow of have those two lines

  ```
  AuthorizationService(context).createCustomTabsIntentBuilder()
   intent = AuthorizationService(context).getAuthorizationRequestIntent(authRequest)
```

I measured the the exec time of those two lines to around 2 seconds which means that I takes two seconds from the user clicks login until the browser tab shows up.  This is poor UX for the end user. I could implement a spinner or something like that, but it made me wonder if I'm doing it wrong or there is a smarter way? Why are those pieces of code so slow anyways?

**Comment by iainmcgin** [comment]
If the user's browser supports custom tabs (right now, most Chromium based browsers do), AuthorizationService will create a bound service connection to the browser in order to perform a "warm up" that makes the custom tab load faster. As such, you should create your AuthorizationService instance early in your activity's lifecycle to benefit from this warmup, and not at the moment at which you click "sign in".

It's also unclear to me what your first line of code is doing, unless you've stripped out the usage of the intent builder and the arguments passed to it, which also provide further speed-up for loading an authorization page from a set of possible pages if done in advance.
