### ISSUE TITLE
Works for "Sign in" but not "Sign up"

### ISSUE THREAD

**Issue by vladikoff** [openid/AppAuth-Android#331]
Got a strange issue where if the user just `signs in` with an existing account then everything is fine.

But if in the flow I click "New Account" which redirects me to `/signup`, then finishing the flow the RedirectActivity window fails to capture the redirect. Any idea what can go wrong with this?

I'm using an HTTPS:// redirect url, not an app one. 

This same setup works fine on desktop (not with this library)

I can "finish the flow" successfully if I click 

"Open in Chrome" then click on my app instead of Chrome in the android "open in" selection.

<img width=320  src=https://user-images.githubusercontent.com/128755/39005346-fc02e3d6-43cd-11e8-9871-6581b7793acd.png />

<img width=320 src=https://user-images.githubusercontent.com/128755/39005376-09a0f5c8-43ce-11e8-86dd-21077922ee67.png />

`.xml` is 

```xml
        <activity android:name="net.openid.appauth.RedirectUriReceiverActivity">
            <intent-filter>
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data android:scheme="https"
                      android:host="some-example-host.com"
                      android:path="/redirect.html"/>
            </intent-filter>
        </activity>
```

Originally filed this here https://github.com/FormidableLabs/react-native-app-auth/issues/99 but i have a feeling it is a bug with this library

Is there some logic where if the URL changes from some-example-host.com/signin to some-example-host.com/signup then it won't properly redirect?

**Comment by vladikoff** [comment]
Might be related to https://github.com/openid/AppAuth-Android/issues/182

**Comment by iainmcgin** [comment]
The decision whether to send the redirect back to the RedirectUriReceiverActivity is made by the browser. There are cases where the browser will refuse to redirect back to the app and instead will load the actual web URL, such as when the redirect is not triggered by Javascript rather than a user action like a button click. I'd have a look to see if the signup flow is doing any automatic redirection when it completes, and if that system is under your control, fix it there. If it's not under your control, I would configure your "redirect.html" to show a page that says "Welcome back" with a button to click to return to the app. That button click can trigger a secondary redirect URI (which you would need to register in your manifest), or a custom scheme URI.

**Comment by vladikoff** [comment]
@iainmcgin thank you for your response, 

> if that system is under your control, fix it there.

we did just that. When I first discovered this I was a bit shocked, I didn't see any useful logging either, so it seemed just broken Android behaviour. Thanks again
