### ISSUE TITLE
Feature Requested: Allow Custom Tab to show webpage title

### ISSUE THREAD

**Issue by NgSekLong** [openid/AppAuth-Android#358]
First of all thank you for this awesome library! Back to topic:

**_Issue Summary:_**
We want to show **webpage title** when user is redirected to the **custom tab**. Which is currently not possible due to code constrain.

**_Research:_**
We found that the below line of code in https://github.com/openid/AppAuth-Android/blob/0.7.0/library/java/net/openid/appauth/AuthorizationService.java#L367

```
intent.putExtra(CustomTabsIntent.EXTRA_TITLE_VISIBILITY_STATE, CustomTabsIntent.NO_TITLE);
```
Will make sure custom tab title is not visible, no matter how I set it. 

As in the documentation, default for `CustomTabsIntent.EXTRA_TITLE_VISIBILITY_STATE`  is already `CustomTabsIntent.NO_TITLE`, so _I assume the purpose of the line of code is to reject people from using title in custom tab_.

**_Request:_**
I would like to ask if it is possible to loosen this restriction, and **allow us to add in title for the custom tab**. Since we think adding in a title will make the authentication UX better. 

Thanks!

**Comment by iainmcgin** [comment]
Hi there,

Digging back through the commit history, that line of code is pretty old and comes from the initial contribution of code from when I was at Google, two years ago, so there isn't a specific explanation of its intent through a commit message.

My guess at our intentions here was either that this was intended to be a default rather than an override, or that we were paranoid about misleading page titles making the UX worse.

Anyway, upon consideration I think this should just be a default, and if the app provides its own custom tab intent with titles enabled we should permit that. So, I'll mark this as a feature request for the next point release.

**Comment by NgSekLong** [comment]
Thanks!
