### ISSUE TITLE
User cancel flow - Prompt the user with the login again

### ISSUE THREAD

**Issue by bblackbelt** [openid/AppAuth-Android#390]
I am using `getAuthorizationRequestIntent` with `startActivityForResult`. I have the following issue:

 - User starts flow and gets prompter with the login on the default brower.
 - User presses back
 - User tries to start the flow again 

I am not able to get back the input fields on the browser where user can input username/password. I can see for a split of second the browser open and close immediatly. I have `RedirectUriReceiverActivity `in the AndroidManifes. am I doing something wrong?

Please advice.

**Comment by BulatMukhutdinov** [comment]
@bblackbelt did you find a solution?

**Comment by mehrdad-shokri** [comment]
Having the same problem here

**Comment by agologan** [comment]
@mehrdad-shokri try creating a new issue/question providing as much information as possible.

This was reported a very long time ago, using an old library version.
Your use-case may not apply.

**Comment by mehrdad-shokri** [comment]
I was able to solve this problem by adding ``promptValues: ['login']`` to ``AuthorizationTokenRequest``

**Comment by agologan** [comment]
Declaring `prompt` as `login` will ask your authorization server to prompt the end-user to reauthenticate which might not be what you're looking for.

Here's a scenario that goes into further detail:
1. User starts the app, taps login and logs into the webView.
2. WebView gets dismissed with the app receiving a token for this session.
3. Assume you didn't save the token and now the user restarts the app.
4. User taps login again.
5. Because the user did not log out of his previous session (assuming it did not expire) and cookies are present the webView, it should be presented an automatically dismissed with the app getting a new token.

Now if the app provides `"prompt": "login"` on the second attempt the user will always be prompted to relogin despite his session saved in the cookies still being valid.

_Feel free to open a new issue - question if you want to go into further detail._

**Comment by mehrdad-shokri** [comment]
Yes, that's correct. But since I'm storing refresh token; on restarts, I just get Token from server.
