### ISSUE TITLE
Problem with App Linking redirects

### ISSUE THREAD

**Issue by iroyo** [openid/AppAuth-Android#434]
I've encountered a problem with App Linking. I have correctly set it up on the AndroidManifest and I have the assetlinks.json on the server. When I get to the last step it seems it should trigger the redirect, but nothing happens, the weird thing is when I go to "Open in Chrome" then the redirect happens and I receive the information carried by the url. So the configuration is correct? Am I missing something?

**Comment by oselvi** [comment]
i'm having the same issue. Redirect url doesnt't trigger the activity and getting 404 error but when i go to "Open in Chrome" it works.

**Comment by agustinsivoplas** [comment]
Same issue here, the difference is the first time works, if you close the app and open again, the second time does not work (session already exist in the browser). We added a dummy page that says "If redirect doest not work, please click here" But is a really bad user experience

**Comment by agologan** [comment]
@agustinsivoplas App Links might not be implemented correctly.
Here's a more recent reply of somebody stumbling upon working the first time: https://github.com/openid/AppAuth-Android/issues/647#issuecomment-779319412

@oselvi, @iroyo App Links have improved slightly over the years - in how they work in Chrome and other browsers, but also in how the caching works when installing the app in Android studio, or upgrade scenarios from Play Store.
As such, I'm closing this issue since it may be out of date.
And I encourage you open a new issue if you're still having problems.
