### ISSUE TITLE
setNonce

### ISSUE THREAD

**Issue by moshtagh** [openid/AppAuth-Android#470]
latest binary has not AuthorizationRequest.Builder::setNonce while repository code has!

**Comment by arthurkamsu** [comment]
I am not sure about why it's not visible. But pass it as an additional parameter. I did this and it worked for me.

```
Map<String,String> params = new HashMap<>();
            params.put("nonce","Your nonce here");
            builder.setAdditionalParameters(params);
```

**Comment by agologan** [comment]
The changes in question were not available in the release at the time of this issue but have been a part of the lib since `0.8.0`.
`setAdditionalParameters` is also a good suggestion for adding parameters which are not yet supported by the lib.

Closing this issue. Feel free to [open a new one](https://github.com/openid/AppAuth-Android/issues/new/choose) if you experience other problems. 👍
