### ISSUE TITLE
appauth login page/browser not getting closed

### ISSUE THREAD

**Issue by bhuvaneshwariarkala** [openid/AppAuth-Android#497]
Hi,

We are using appauth for authentication in android . We were able to login successively, but when we redirect to our app scree, the login browser not getting closed. It still remains open, so when we close our app, the app auth login browser still exists.
What can I do to close this scren?

**Comment by mdcuk34** [comment]
We're also now getting this, did you find the reason why?

**Comment by sundeepkmallick** [comment]
This post seems to be old. But if any developer struggling with same problem, please use Android App Links to solve your problem. Also more secured way. Your app's minSdkVersion should be 23 to implement below:
https://developer.android.com/studio/write/app-link-indexing 
https://developer.android.com/training/app-links/verify-site-associations

**Comment by agologan** [comment]
Agree that verifying the redirectScheme or App Links work correctly should be a first step.

Since this is an old issue, and doesn't provide enough information to take further action, I'll be closing this. Feel free to [open a new one](https://github.com/openid/AppAuth-Android/issues/new/choose) if you still experience this problem and can provide further information. 👍
