### ISSUE TITLE
Displaying URL when we are login using OpenId.

### ISSUE THREAD

**Issue by manjith-pt** [openid/AppAuth-Android#509]
When I login using openId it is redirecting to in app browser, which is displaying URL in the app. Can we hide that URL

**Comment by iainmcgin** [comment]
The URL can only be hidden if you can meet the requirements for a trusted web activity: https://developers.google.com/web/updates/2019/02/using-twa

In short, if the authorization URL is provably associated to your app, through an app association, you can display the web content without any decoration similar to how a web view behaves. If you're using a third party IDP (e.g. Google, Okta, etc) then you won't be able to do this and the URL display is required, so that the user knows they can trust interacting with the IDP flow.
