### ISSUE TITLE
refreshtoken null

### ISSUE THREAD

**Issue by slowcar** [openid/AppAuth-Android#523]
Our application uses this library against Microsoft oauth v2, and usually without any issues.
We call AuthState.performActionWithFreshTokens for every operation, for example every 15m in a background worker.
At some point this operation fails and we get a CLIENT_ERROR indicating that mRefreshToken is null (line 540 in AuthState). How can that happen if we refreshed the token 15 minutes before?
How do we recover from this state?

**Comment by agologan** [comment]
It shouldn't happen but there's not enough information in your question to help debug the issue.

Since there are only a handful of places where mRefreshToken is assigned, recommend you debug your issue and get back with more information.

Judging by the fact you mentioned a background worker, I wouldn't be surprised if your state gets accidentally changed during between calls.

**Comment by iainmcgin** [comment]
Are you persisting and reloading your auth state between these intervals? Like @agologan suggests, I think you will need to trace possible changes to the AuthState structure, and my instinct would be to check for serialization or aliasing issues.

**Comment by slowcar** [comment]
We have switched to Microsoft MSAL, so i won't be able to debug the issue further, sorry about that.
