### ISSUE TITLE
FileNotFoundException when called performRegistrationRequest() method

### ISSUE THREAD

**Issue by technikhil314** [openid/AppAuth-Android#539]
I am using keycloak as my openid authentication server for my android app. User login is working just fine. But when I call performRegistrationRequest method on click of a button when user wants to register with my application. It gives me following error. 

java.io.FileNotFoundException: https://keycloak-server-base-url/auth/realms/meraklis-platform/clients-registrations/openid-connect

First of all is it correct to call performRegistrationRequest when user wants to register??

If yes what am I missing??

If no how can I make user register to my keycloak server??

**Comment by iainmcgin** [comment]
If the error you describe is literally what you see, i.e. the exception is for URL `https://keycloak-server-base-url/auth/realms/meraklis-platform/clients-registrations/openid-connect`, then this is likely because `keycloak-server-base-url` is not a valid host name and you need to substitute this for your actual keycloak server host name.
