### ISSUE TITLE
New release schedule

### ISSUE THREAD

**Issue by chrismash2** [openid/AppAuth-Android#578]
Hi,

It's been 2 years since the last release and there are quite a few things that have been added since then. Is there any planned time for the next release? (I know there have been issues with a lack of maintainers)

FWIW I'm specifically looking at getting the nonce sent on the auth request, which isn't part of 1.7.1, but seems to all be there on master.

**Comment by hnljp** [comment]
You can use a snapshot of the current master, if you are unable to wait for the next release:
https://jitpack.io/#openid/AppAuth-Android/27b62d5da9

**Comment by mabae** [comment]
+1 for a release schedule, a roadmap or any other statement on the state/future of this library. Working with snapshots is not cool.

**Comment by childnode** [comment]
indeed, a release needed at least for #558 
what are the TODOs needed for a release? perhaps someone can point this out and perhaps then there are some contributors available to do this?

**Comment by AshaRamanjanaiah** [comment]
I used snapshot but still the app crashes when tried to login. Did anyone tried using snapshot?

**Comment by hnljp** [comment]
> I used snapshot but still the app crashes when tried to login. Did anyone tried using snapshot?

@AshaRamanjanaiah 
It is working "perfectly" here, have been using it for production builds for a while now.
How does it crash for you?

**Comment by ericsimmons** [comment]
On Thu, Oct 1, 2020, 2:59 AM Henning Lund <notifications@github.com> wrote:

> I used snapshot but still the app crashes when tried to login. Did anyone
> tried using snapshot?
>
> @AshaRamanjanaiah <https://github.com/AshaRamanjanaiah>
> It is working "perfectly" here, have been using it for production builds
> for a while now.
> How does it crash for you?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on
> <https://github.com/openid/AppAuth-Android/issues/578#issuecomment-701931100>
> https://github.com/AshaRamanjanaiahGit
>

Hub, or unsubscribe

**Comment by carstenhag** [comment]
Hello there, asking as well if we could have a real release. I know that it's possible to get one via jitpack, but it's not the real deal of course :)

**Comment by dsuresh-ap** [comment]
Is there a reason why we haven't had a release in over 2 years?

**Comment by agologan** [comment]
There hasn't been a new release because there hasn't much maintainer availability until recently #444 .

We are looking into cutting a new release with support for Android 11 and end session functionality, but we rely on the feedback from the community to ensure it meets expectations.
As such, we hope at least some developers would try out master/snapshot builds and provide feedback via issues and PRs.

**Comment by 3flex** [comment]
Thanks @agologan for your work to continue maintaining the project!

I don't think I agree with the approach of seeking feedback prior to a release before cutting one - instead why not release 0.8.0-rc (or just 0.8.0, since the library hasn't hit a "stable" 1.0 release yet even though the core functionality is there).

I think many would cheer for a new release (on Maven Central!) Even if the new features turn out to have some bugs the release would give more confidence that the project is actively maintained. It would also be better to have the version that properly supports Android 11 and AndroidX released with possible bugs instead of the last official release, which is over 2 years old, that doesn't.

Just my 2c.

**Comment by agologan** [comment]
@3flex interesting perspective. I'm more used to getting feedback before pushing something out in the wild rather than releasing something and hoping it sticks.

Anyway, in this case I do agree that a new version is required so here you go [0.8.0](https://search.maven.org/search?q=g:net.openid%20appauth) via MavenCentral.

Marking this topic as resolved for now.

**Comment by 3flex** [comment]
Don't get me wrong, I'm not calling for a reckless approach! Snapshots and RCs are great to get feedback.

I think the main thing going forward is just that there's a more regular release cadence via official channels. There are various criticisms of jitpack that I've seen while people were evaluating alternatives to jcenter and bintray now they're going away so I think people will be happy that you've setup publishing to Maven Central.

Again, thanks for your work on this!
