### ISSUE TITLE
AppAuth sample works, but own implementation doesn't

### ISSUE THREAD

**Issue by ghosalmartin** [openid/AppAuth-Android#647]
Using a `https` redirect with my own implementation causes the redirect to stay in the Chrome Custom Tab. But if I implant it in the AppAuth sample app it works.

I've discovered this is because of the `executor` here:

https://github.com/openid/AppAuth-Android/blob/master/app/java/net/openid/appauthdemo/LoginActivity.java#L462

But can't seem to recreate the effect for my own code. Is that behaviour intentional? Do we need to wait for the browser to warm up?

Cheers
Martin

**Comment by agologan** [comment]
Warming up the browser is not required, it's just possible speed improvement for custom tabs. https://github.com/openid/AppAuth-Android/commit/de0ed1ad9b2362c1b27dfb3c1d2e6c8f13d699b4
More here: https://developer.chrome.com/docs/multidevice/android/customtabs/#warm-up-chrome-to-make-pages-load-faster
This has some benefit in the demo because there's an obvious delay between the user selecting the browser and starting the authorization flow.

Under normal circumstances, a user would just tap a login button and expect to be prompted with the identity provider without needing to deal with browser selection. In this case just call the authorization request without specifying a custom tabs intent and let the lib decide from available browsers which is best suited. (similar to App Auth heuristic selection in the demo).

Whichever the case we require further information about your configuration in order to help you.
Also note, that `https` requires App Links support to function properly or you'll end up with a disambiguation dialog.

**Comment by ghosalmartin** [comment]
I don't have an issue with that dialog thankfully. But unless I put it all on a single thread then the redirect uri gets triggered in the chrome tab rather than redirecting properly.

I can setup a sample project highlighting the issue?

**Comment by agologan** [comment]
Please do. Having a sample project highlighting the issue would be helpful.

**Comment by ghosalmartin** [comment]
here ya go 

https://github.com/ghosalmartin/AppAuth-Threading-Break

**Comment by agologan** [comment]
Thank you for the sample.
Upon initial inspection it's interesting it works once (might have something to do it's not a production app ¯\_(ツ)_/¯)

Where it breaks, even in the working demo is if you tap login a second time.
You're still greeted with the okta 404 because the redirect you configured is a bogus link (okta/test)
What isn't so obvious is if you go and select **open in chrome...** then you're greeted with a disambiguation dialog which points to the reason this doesn't work: [App Links](https://developer.android.com/training/app-links)

If you want to use an `https` redirect than you need to configure App Links on your own domain, otherwise just use a custom schema.

**Comment by ghosalmartin** [comment]
Yeah the 2nd time am guessing its the timing issue. So its too fast and putting it on a different thread seems to negate that for the first attempt.

**Comment by agologan** [comment]
I think you misunderstood my comment.
It's accidental it works the way it does the first time.

What you should be seeing is a disambiguation dialog in both cases but it really depends on the browser, version and the way the redirect is done server-side.

Please look at implementing App Links or using a custom redirect scheme to get your workflow going end-to-end correctly.

**Comment by ghosalmartin** [comment]
Oh definitely. Some weird bug that's occurring that makes it "work" when it shouldn't.

I can confirm that's the case because if I do use a custom redirect scheme it works perfectly.

**Comment by agologan** [comment]
In regards, still seeing the disambiguation dialog when using App Links - there might've been an issue in the past, but recent tests point to the fact that debug builds work just fine as long as you configured the correct debug fingerprint and your device has up to date the domain information.

As for the second part changes to Chrome iframe and custom uris should not affect either App Links or custom URI redirects as an identity provider is not supposed to implement the client callback using that strategy.

There also shouldn't be any issue with preexisting cookies but it's up to the identity provider to do proper redirection and not the app developer.

**Comment by agologan** [comment]
Moving to **close** this topic as we've strayed far enough from the original topic.

_Feel free to open a new issue if you feel that you have further specific questions._

**Comment by ghosalmartin** [comment]
That's fine, thanks for the replies :)
