### ISSUE TITLE
Trusted Web Activity not removing URL bar

### ISSUE THREAD

**Issue by maddymvn** [openid/AppAuth-Android#653]
The URL bar not showing when we set the Samsung browser as default. if we use chrome or firefox as default browser we can able to see the URL bar.

I used the below intent for customtabs
customTabsIntent.intent.putExtra(EXTRA_LAUNCH_AS_TRUSTED_WEB_ACTIVITY, true)

We successfully configured the digital asset links and tested with the ([https://developers.google.com/digital-asset-links/tools/generator]) it is working fine.
![108048853-8b8dbc00-706d-11eb-8ce4-590b52be8a4c](https://user-images.githubusercontent.com/21606857/108081738-4aaa9d00-7097-11eb-910b-d3eed5fa6b00.png)

**Comment by agologan** [comment]
> EXTRA_LAUNCH_AS_TRUSTED_WEB_ACTIVITY
> Boolean extra that triggers a CustomTabsIntent launch to be in a fullscreen UI with no browser controls.
src: https://developer.android.com/reference/androidx/browser/customtabs/TrustedWebUtils

Sounds like you want this set to `false`.
Also, differences between browser implementations you have to take up with the individual developers.
It is not our responsibility to make sure the browsers are in line, we're just consumers of the API.

**Comment by mathavanmanoharan** [comment]
Thanks for your response. 

Here I need to hide the URL bar in the browser. 

if I launch the EXTRA_LAUNCH_AS_TRUSTED_WEB_ACTIVITY = true means, it is removing perfectly in the samsung browser. but in the chrome browser it is nor removing the URL bar. 

if I directly use the EXTRA_LAUNCH_AS_TRUSTED_WEB_ACTIVITY without your app means it is working fine.

**Comment by agologan** [comment]
Any difference in behavior in browsers should be taken up with the browser developers.

_Marking this as closed for now.
Feel free to open a new topic in regards to this library in particular._

**Comment by mathavanmanoharan** [comment]
We had the asset link verification in the server side and client side also. When we use Trusted web activity directly without your library means URL bar is hiding and it is working fine. 

When we use the same with **your library** with **Trusted WebActivity** in the **CustomTabIntent** means we got the toast as **Digital asset verification failed on the <url> with client id** and so on. then we can see the URl bar. the Problem is only happens when we use your library.

![Screenshot_20210211-164941_Chrome (1)](https://user-images.githubusercontent.com/65548862/109624040-c1e63380-7b63-11eb-830e-ba6db03ec4a3.jpg)

**Comment by agologan** [comment]
I'm sorry but I still don't understand what the link is between EXTRA_LAUNCH_AS_TRUSTED_WEB_ACTIVITY , digital asset links verification and this library.

**Comment by ganesh-ic** [comment]
@mathavanmanoharan have you found the fixes for your problem? would you kindly share the fixes, thanks!
