### ISSUE TITLE
Deep linking sometimes not working on page returning non 200

### ISSUE THREAD

**Issue by stephen1706** [openid/AppAuth-Android#661]
Hi, I have setup a https deeplink properly, sometimes the deeplink works on the authorization flow, but some other time it does not intercept and close the custom tabs. I think possibly because the page is returning 404 in the front end. Is there any configuration to force intercept the deep link regardless of the http return code?
Thank you

**Comment by agologan** [comment]
The redirect will work all the time if you've implemented [App Links](https://developer.android.com/training/app-links)

**Comment by kawomm** [comment]
To be honest, I followed the instructions behind the link above and also have some interception issues. On the emulator the first time (after booting the virtual device) it works as expected, but any subsequent call the interception fails somehow (see also [https://github.com/openid/AppAuth-Android/issues/67]

**Comment by agologan** [comment]
I kinda expected a reply telling me you validated App Links and it still doesn't work, or that you resolved your issue.
In the meantime discussing the topic with others I did realize you may be running into a redirect issue as described here: https://github.com/openid/AppAuth-Android/issues/679 

The problem will occur if the user is authenticated in the browser and the identity server wants to auto-redirect back to the app without user interaction.
My recommendation: have the user tap his profile if he's logged in to confirm his intention instead of automatically redirecting.

**Comment by agologan** [comment]
_Closing this as there has been no response from the OP in a reasonable amount of time. Assuming issue has been resolved. Feel free to [open a new issue](https://github.com/openid/AppAuth-Android/issues/new/choose) if you require further assistance 👍_
