### ISSUE TITLE
endSession() not working properly, giving me "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable." error

### ISSUE THREAD

**Issue by MonikaMoon** [openid/AppAuth-Android#674]
I am following the code above for end session, I have tried with demo code of TokenActivity.endSession() as well but still unable to end session on my device.

My final url looks like:
httpsBaseURL/end_session?id_token_hint="idToken"&post_logout_redirect_uri=httpsBaseURL/logout

but its giving me error as follows:
"The resource you are looking for has been removed, had its name changed, or is temporarily unavailable."

I am not sure why I am unable to end session properly.

**Comment by agologan** [comment]
As @Barryrowe metioned here https://github.com/openid/AppAuth-Android/pull/433#issuecomment-801967475 the issue is regarding to providing an incorrect path assuming your Identity Provider supports the logout workflow.

Easiest way to check if it's supported is to look for `end_session_endpoint` in `https://idp.example.com/.well-known/openid-configuration`.

- If it is there but your config was incorrect I suggest you use `AuthorizationServiceConfiguration.fetchFromIssuer()` instead of manually providing a configuration.
- If it is there and your config matches is then please contact your Identity Provider and notify him of the issue
- If there is no `end_session_endpoint` you can assume your Identiy Provider doesn't implement a logout workflow and you can just delete your saved session in app.

**Comment by MonikaMoon** [comment]
@agologan Thanks for your response. Able to solve the issue by changing the redirect and discovery uri's. Your comment helped me get to the root cause of my issue.

**Comment by bhavnamulani** [comment]
Hi All,
I have implemented appauth, and my login is successful but whenever I am trying to log out it says session_not_active.
I have tried to persist in my session.
why is always say the session is not active even if the login is successful and I am getting user info too?
