### ISSUE TITLE
New version of the library

### ISSUE THREAD

**Issue by rebeckag** [openid/AppAuth-Android#68]
Just to gather some changes; when the dynamic client registration is completed (as of #61), is this library ready for v0.3.0 soon?
PR #66 and #67 are contingent on a new version (and should not be merged until that is released).
In connection with a new version, the javadoc hosted at the github pages will also need to be re-generated.

**Comment by iainmcgin** [comment]
Yes, I've been meaning to cut a new version, especially now we have all your changes in. I don't mind if the README.md discusses API surfaces that only exist at HEAD, since the API is expected to be in flux until we decide it's good enough for 1.0.0, so we don't need to block the merging of the other changes until 0.3.0 is cut.

**Comment by DavidCorrado** [comment]
Any updates on this? Is it possible to get the next version built?  I am looking into using the feature of using the client_secret.

**Comment by abrunyee** [comment]
I am also trying to use the client_secret, as I'm trying to authorise against IdentityServer which requires the it for token exchange. I built the AppAuth library myself from the master branch, but I'm getting a NoClassDefFoundError exception for BrowserHandler$1 which I'm really struggling to resolve.

**Comment by dewafer** [comment]
@abrunyee Yeah, I've had the same problem. It's because you've directly imported the AAR lib as a module in your project. It seems that won't work.

My solution is use `gradlew clean build install` build and install AppAuth_Android in local repository first, and then in my own project use `mavenLocal` and `compile 'net.openid:appauth:0.2.0+'` in repositories and dependency settings in the build.gradle file, let gradle pickup the newly built one. Also it will automatically move on when the new version is released. (Hope it will be released soon) That works for me.

Hope it helps.

**Comment by abrunyee** [comment]
@dewafer Thanks, that worked great!

**Comment by iainmcgin** [comment]
Sorry for the delay here, things have been incredibly busy for me these past few months. I've just published 0.3.0 to bintray.
