### ISSUE TITLE
Prompt Issue from B2C - Google authentication.

### ISSUE THREAD

**Issue by Saitarak436** [openid/AppAuth-Android#683]
Hi everyone,

I had an issue with App auth android for google Authentication.

Sharing you the below code for understanding purpose :

```java
AuthorizationServiceConfiguration serviceConfig = new AuthorizationServiceConfiguration(
        Uri.parse(Constants.Authorization_endpoint), // authorization endpoint
        Uri.parse(Constants.Token_endpoint) // token endpoint
);
String clientId = Constants.ClientID;
Uri redirectUri = Uri.parse(Constants.REDIRECT_URL);
AuthorizationRequest.Builder builder = new 
AuthorizationRequest.Builder(serviceConfig,clientId,"code",redirectUri);
builder.setScopes(new String[]{Constants.Scope});
builder.setPrompt(Constants.Prompt);
AuthorizationRequest authorizationRequest = builder.build();
AuthorizationRequest authRequest = authorizationRequest;
AuthorizationService authService = new AuthorizationService(Login.this);
Intent authIntent = authService.getAuthorizationRequestIntent(authRequest);
startActivityForResult(authIntent,RC_AUTH);
```

Setting Prompt as 'select_account', It was appending to my B2C link. but when it comes to Google Authentication i havent seen Prompt as per below:

https://accounts.google.com/o/oauth2/auth/oauthchooseaccount?client_id={cliennId}&redirect_uri=https:B2Clogin.com/{tenantId}%2Foauth2%2Fauthresp&response_type=code&scope=email%20profile&state=StateProperties%3DeyJTSUQiOiJ4LW1zLWNwaW0tcmM6ZDQwMjE3NGQtODY4ZC00ZTQyLThmODAtYmRhNzc5ZDRjM2ViIiwiVElEIjoiZWE1ZTJjZDEtNjA2NS00MmM5LTlhNDQtNTAyMWVkNzRlZGZkIiwiVE9JRCI6ImZhNTJhMzAxLTg1OWQtNDVlNC04YWEwLTkzZDNiYTBkNjViYyJ9&flowName=GeneralOAuthFlow

if you can observe prompt is not appending here.

**Comment by agologan** [comment]
I'm assuming the issue that you are describing is related to the fact that B2C is not appending the prompt you requested when redirecting to Google.
If so that is an integrator issue and you should reach out to the team at Microsoft for help.

If I misunderstood your ask than please try to bring further information to clarify the issue.
FYI: You don't need to redeclare standard scope and prompt values as they are available in [AuthorizationRequest.java](https://github.com/openid/AppAuth-Android/blob/master/library/java/net/openid/appauth/AuthorizationRequest.java#L173)

**Comment by agologan** [comment]
Closing this as there has been no response from the OP in a reasonable amount of time. Assuming issue has been resolved. Feel free to [open a new issue](https://github.com/openid/AppAuth-Android/issues/new/choose) if you require further assistance 👍
