### ISSUE TITLE
Hide the url when we open the page.

### ISSUE THREAD

**Issue by Stephen-Massive** [openid/AppAuth-Android#687]
### Configuration
- Version: 0.7.0

### Description
If we can hide the URL in the browser. I found this https://github.com/openid/AppAuth-Android/issues/277 answers, it's is 2017.
Can we do it now. It's 2021 now.

**Comment by agologan** [comment]
This has been possible with the introduction of Trusted Web Activities and [TrusteWebUtils](https://developer.android.com/reference/android/support/customtabs/TrustedWebUtils.html) at the end of 2017.
Since 2019 you can just add `EXTRA_LAUNCH_AS_TRUSTED_WEB_ACTIVITY` to the `CustomTabsIntent` as explained here #292 
But to get rid of the URL bar you actually have to associate your app with the server [TrustedWebActivity#RemoveUrlBar](https://developer.chrome.com/docs/android/trusted-web-activity/integration-guide/#remove-url-bar)

**Comment by rodrigo-lima** [comment]
@agologan - I understand that per RFC-8252's recommendation we should **not** hide the *address bar*, but would it then be possible to hide only the *share-button* and the *more-vertical* (3 dots) buttons? 

![custom-tab](https://user-images.githubusercontent.com/326489/123329191-2574e200-d502-11eb-86d9-33131a21bbbf.png)

**Comment by agologan** [comment]
There is no API to achieve what you want.
You can either implement TWA which will result in a fullscreen experience or use custom tabs as is.
If you want a different behavior you should take it up with the chrome team which are behind the Custom Tabs API.

**Comment by KevinAlexanderSoto** [comment]
> @agologan - I understand that per RFC-8252's recommendation we should **not** hide the _address bar_, but would it then be possible to hide only the _share-button_ and the _more-vertical_ (3 dots) buttons?
> 
> ![custom-tab](https://user-images.githubusercontent.com/326489/123329191-2574e200-d502-11eb-86d9-33131a21bbbf.png)

You can hide the share-button by adding `.setShareState(CustomTabsIntent.SHARE_STATE_OFF)` to the CustomTabs builder. You can find more in the Doc ( https://developer.chrome.com/docs/android/custom-tabs/guide-interactivity/ )
