### ISSUE TITLE
User Registration

### ISSUE THREAD

**Issue by gary-doolin** [openid/AppAuth-Android#688]
### Configuration
- Version: 0.8.1
- Integration: Native Kotlin
- Identity provider: Key Cloak

### Description
Hi, 

I've implemented login via appauth/keycloak.  I am wondering how app auth handles user registration?  Is there an intent other than the auth intent or end session intent to launch?  

I might be missing something, or perhaps it doesn't support user reg?

**Comment by gary-doolin** [comment]
Issue resolved.  I sourced the info elsewhere

**Comment by sebastianmarschall** [comment]
@gary-doolin where did you find the info? thanks!

**Comment by gary-doolin** [comment]
@sebastianmarschall General research and I requested info on stack overflow. Unfortunately it wasn't the answer I had hoped for but I knew then we needed to take that route of registering the user via an option on the sign up form 
https://stackoverflow.com/questions/67095964/registering-user-with-appauth

**Comment by sebastianmarschall** [comment]
@gary-doolin thanks for the info, much appreciated. i'm currently researching on the same topic. did your registration also include email verification? i'm wondering if a smooth user flow (like for login with redirect) is even possible for registration? i guess not since we won't have a deep link back into the app with the auth token?
