### ISSUE TITLE
getting crash in crashlytics "Fatal Exception: java.lang.IllegalStateException No authorization configuration available for refresh request net.openid.appauth.AuthState.createTokenRefreshRequest"

### ISSUE THREAD

**Issue by Malviyapneha** [openid/AppAuth-Android#695]
```
Fatal Exception: java.lang.IllegalStateException: **No authorization configuration available for refresh request**
       at net.openid.appauth.AuthState.createTokenRefreshRequest(AuthState.java:615)
       at net.openid.appauth.AuthState.createTokenRefreshRequest(AuthState.java:601)
       at com.repository.LoginRepository$performRefreshTokenRequest$1.invokeSuspend(LoginRepository.java:66)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:106)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:571)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.java:738)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.java:678)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.java:665)
```

I am updating AuthorizationResponse also once receiving response, but getting this crash on refreshing token. Thing is it is not happening on all devices.

**Comment by agologan** [comment]
The exception comes from https://github.com/openid/AppAuth-Android/blob/master/library/java/net/openid/appauth/AuthState.java#L615
Recommend you debug your state information and try to figure out why `mLastAuthorizationResponse` is now `null`.

**Comment by Malviyapneha** [comment]
@agologan  thanks for your response. I understand it is crashing because mLastAuthorizationResponse is becoming null, but i have debugged alot i am not getting why this value is becoming null, I am updating "AuthorizationResponse"  but still, it is becoming null that to not every time and not in all devices. I am using 0.7.1 version of AppAuth library, is their any issue with this version?

**Comment by agologan** [comment]
I personally don't know if any issue.
You can either run into this problem by calling `AuthState#update` with a **null** reponse or by messing with the saved json `AuthState`.
If I'd have to guess it's the former issue.

**Comment by JohannesTeichert** [comment]
I just stumbled upon this thread and was about to ask for help because I had the same exception, looking once more over my own code I realized that I did not update my authState with the AuthorizationResponse.

for me it works now like that:

after logging in the intent provides me with an AuthorizationResponse or AuthorizationException
`val authorizationResponse = AuthorizationResponse.fromIntent(data)`
`val authorizationException = AuthorizationException.fromIntent(data)`

update authState with response and exception
`authState?.update(authorizationResponse, authorizationException)`

then I exchange the authcode for the actual tokens:
`authService.performTokenRequest(authorizationResponse.createTokenExchangeRequest()) { tokenResponse, exception ->`
`     authState.update(tokenResponse, exception)`
 `    //do something with tokens or persist them, e.g.:  authState.accessToken` 

then when I come back to try to cal createTokenRefreshRequest the lastAuthorizationResponse is not null anymore and the refresh works perfectly.

`val tokenRefreshRequest = authState.createTokenRefreshRequest()`
`            authService.performTokenRequest(tokenRefreshRequest) { response, exception ->`
`                //again dont forget to update authstate`
`                authState.update(response, exception)`
`                //do something with tokens or persist them, e.g.: authState.accessToken` 

maybe that helps you as well

**Comment by Malviyapneha** [comment]
@JohannesTeichert  I am already following above steps, but still it is crashing ,Not every time in all device but randomly specially for android version 10.

**Comment by agologan** [comment]
_Closing this as there has been no response to our request for more information from the OP in a reasonable amount of time. Assuming issue has been resolved. Feel free to [open a new one](https://github.com/openid/AppAuth-Android/issues/new/choose) if you still experience this problem and can provide further information 👍_

**Comment by Voto** [comment]
We ran into this issue too. The challenge and from my opinion wrong behaviour is that you get this error only once per app session. 
We get this error from `AuthState` here
``` java
 @NonNull
    public TokenRequest createTokenRefreshRequest(
            @NonNull Map<String, String> additionalParameters) {
        if (mRefreshToken == null) {
            throw new IllegalStateException("No refresh token available for refresh request");
        }
        if (mLastAuthorizationResponse == null) {
            throw new IllegalStateException(
                    "No authorization configuration available for refresh request"); // <--- origin of exception line 636
        }
```

Throwing this error should also clear `mPendingActions` as the last action was canceled due to error. Because `AuthState` did not clear it each further request end here silently in `performActionWithFreshTokens()`:
``` java
 synchronized (mPendingActionsSyncObject) {
            //if a token request is currently executing, queue the actions instead
            if (mPendingActions != null) { // <--- game over 
                mPendingActions.add(action);
                return;
            }
```

We actually solved our issue by a workaround. Our implementation uses a non-standard one-time-password for a seamless login after a user registers a new account. So we feed the `AuthStateManager` with a fake `AuthorizationResponse`

``` java
val authorizationResponse = AuthorizationResponse
                .Builder(authRequest)
                .setAccessToken(accessTokenResponse.access_token)
                .build()
            authStateManager.updateAfterAuthorization(authorizationResponse, null) // <-- feed the response
            authStateManager.rewriteUpdatedAuthState()
```

**Comment by camina-apps** [comment]
Ran also into the issue. Our workaround is by checking if the lastAuthorizationResponse is not null before creating the tokenRefreshRequest and log out user if that is the case. 

@Voto Explains the root cause perfectly. I think this bug report should be reopened
