### ISSUE TITLE
RedirectUriReceiverActivity is not getting called on new Huawei device models.

### ISSUE THREAD

**Issue by ThatsNeha** [openid/AppAuth-Android#703]
Hi Team,
We have integrated AppAuth in our application. It is working fine on all the devices except new model of huawei (Huawei Y7a,Huawei Mate40)  where it is not getting redirected back to application (RedirectUriReceiverActivity is not getting called ).

**Comment by agologan** [comment]
Assuming these devices are running HMS (Huawei Mobile services) and you are trying to use App Links as described by Google which require GMS (Google Mobile Services).
I haven't tested this myself but you have to register your link in AG connect to make them work.

More info: https://stackoverflow.com/questions/66204537/how-to-support-app-linking-on-huawei-devices-with-hms
https://developer.huawei.com/consumer/en/doc/development/AppGallery-connect-Guides/agc-applinking-createlinks-byagc-0000001058988077

**Comment by ThatsNeha** [comment]
@agologan  But this app is working fine on other devices in china where GMS is blocked, only on huawei devices we are seeing this redirection issue.

**Comment by agologan** [comment]
_I'm sorry I made an incorrect assumption based on improper research of the topic._

It seems that Asset Links are verified by the `pm` which invokes the `statementservice` after the package is installed and does not require any GMS interaction.

I should've instead probably asked what browser are you using and whether or not trying to open the link outside of the browser invokes the disambiguation dialog with your app.

**Comment by ThatsNeha** [comment]
This issue is happening with Huawei default browser. RedirectUriReceiverActivity in not launching. But working fine with other browser in same device.

**Comment by agologan** [comment]
Ohh, well that explains it.
Because it's the browser developer's responsibility to correctly support App Links.
You should get in touch with Huawei developers to get an official statement or a fix.

In the meantime if your users are guaranteed to have other browsers installed you can use `BrowserDenyList` to exclude it from the interaction.

Closing this issue for now as it's outside the scope of this lib, but do let us know of the outcome as other developers may be interested.

**Comment by ThatsNeha** [comment]
Thanks @agologan for your support.
