### ISSUE TITLE
How to forget last session?

### ISSUE THREAD

**Issue by drdla49** [openid/AppAuth-Android#721]
We use AppAuth in uor android app. For normal login with username and password everything works well. But if I use social login (Google, Facebook,...) there is a restored login from the last session.
For example, if I use Google login. When I first log in to the app, there is a dialog with choose credentials. I choose some and I am successfully logged. But when I log out and try to log in again, there is no dialog with credentials, and the user has logged in automatically with the last credentials.
This happens only for social logins.
I think that I can use method setPrompt, but I try all 4 possible values and nothing works.

In our iOS app with AppAuth, everything works, so I think that our identity server works well. 

Is there any other way to show credentials choose dialog?

Thanks

**Comment by agologan** [comment]
Looking at `prompt` is correct but it really depends on your identity provider on how it behaves.
This is true for both logout behavior as well as prompt behavior.
Sounds like iOS does not actually persist the SSO session thus you're getting a different behavior.
You should really take it up with your identity provider as the community here doesn't know the integration details of your solution.

Btw, `prompt: select_account` should show the account picker (if your identity server supports it) and `prompt:login` will ask the user to relogin but since that is delegated to another service it may not work if your identity provider doesn't forward the prompt to that service.
