### ISSUE TITLE
What happens to expiry check if system time is changed by the user?

### ISSUE THREAD

**Issue by ritesh-singh** [openid/AppAuth-Android#747]
### Description
https://github.com/openid/AppAuth-Android/blob/f1dbeb51f4d905523d804d70363abdb00728d99c/library/java/net/openid/appauth/AuthState.java#L323

I see here - that it uses System time to check for the expiry time of the token - before it hits an api. I believe this can be mis-used cannot be correct always - in cases like, user changes the system time.

Why not rely on 401/403 instead of checking the expiry of access token beforehand?

**Comment by agologan** [comment]
If you're referring to using `performActionWithFreshTokens` which in turn checks `getNeedsTokenRefresh` - then I can't exactly say why the original author didn't expand the solution to do HTTP response check also. Maybe because that would require making assumptions on what the `AuthStateAction` as running the code again on 401 may lead to unintended side-effects.

In my own use-case I did not rely on that function and instead wrote an **okhttp** interceptor that does both checks, first a preemptive time check and then the actual request which in case of failure first tries to fetch a new token and retries the request before proceeding returning any response. Obviously my solution makes a lot of assumptions on request behavior and shaping and is not as generic as the library API.

**Comment by ritesh-singh** [comment]
> first a preemptive time check 
@agologan  - are you saying your interceptor is also checking the expired time of token based on system-time. In that case what will happen if system is changed or in different time-zone, or if there's a slight clock skew between server and client.
Why not just rely on 401?  - as in call apis without checking the expiry of token, calling api with expired token will give 401, 401 in interceptor - refresh token and then call the api again from interceptor.
Use of system time can be avoided.

**Comment by agologan** [comment]
Because in most cases it avoids the extra request - call it the fast path.
If the check passes the call is done, if it returns 401 a refresh is done and then the call is retried - the slow path.

**Comment by ritesh-singh** [comment]
Thanks for describing @agologan  - We are not arguing :slightly_smiling_face: , i was putting my point of view.

**Comment by agologan** [comment]
Fair enough. Closing the topic for now.
