### ISSUE TITLE
How to close browser automatically upon successful EndSessionRequest?

### ISSUE THREAD

**Issue by alwa** [openid/AppAuth-Android#799]
### Configuration
Version: 0.11.1
Integration: native (Kotlin)
Identity provider: KeyCloak

### Description
When `authorizationService.performEndSessionRequest()` is invoked the library opens up a browser towards the end session endpoint (in my case an empty page that returns HTTP 200). The user has to manually close down the browser.
Is it possible to close down this browser (activity?) automatically somehow - which is how it works for token requests?

**Comment by alwa** [comment]
Perhaps/probably related but I'm not receiving a callback on the request (because I don't have any redirect URI specified)?

**Comment by agologan** [comment]
In the case of Keycloak, logout works similarly to authorization. Just keep in mind end session requests use the same redirect URI as authorization unless you add another one for end session in your client config in Keycloak.

**Comment by alwa** [comment]
Hi @agologan,
thanks for your update on this.
I finally managed to make it work (by providing the same URI that I had used to configure RedirectUriReceiverActivity.

**Comment by 0verEngineer** [comment]
@alwa Hey, sorry for bothering you, but how did you get it to work with Keycloak? I have the problem that i am not redirected back to the app after logout, i also use Keycloak and it shows no logout promt and no redirect button, so chrome (android webview) blocks the redirect because there was no user interaction. If i attach devtools i can see the log: `Navigation is blocked: app-name://auth/auth_callback?state=GDcOba0zvVdRhZXovHwfUA`.
