### ISSUE TITLE
Move net.openid.appauthdemo.AuthStateManager to library?

### ISSUE THREAD

**Issue by alwa** [openid/AppAuth-Android#812]
### Feature Request
I would like it if the AuthStateManager (found in the app module) could be made available in the library module by moving the class.

#### Motivation
For convenience. 
That way library integrators don't have to make similar implementations and also encourage using the library in the way it was designed. I understand that you want to allow the integrator to use other means of persistance and so on but this would still be possible. Perhaps renaming the class to e.g. `SharedPreferenceAuthStateManager` would clarify things. And allowing the user to pass their own instance of `SharedPreferences` - enabling the user to manage the names, etc.

#### Description
Move `net.openid.appauthdemo.AuthStateManager` to `net.openid.appauth`

#### Alternatives or Workarounds
Copy-paste the source code from the demo app and adapting the source code, possibly convert to Kotlin, to the project naming conventions.

**Comment by DATL4G** [comment]
I don't think that's a good idea.
Google announced and released DataStore some time ago, which offers some advantages over SharedPreferences.
Some developers have already completely switched to this method and no longer use SharedPreferences at all.
So there is no one-size-fits-all solution.

The current "abstraction" is better because everyone can decide for themselves which storage method they use. Finally, you only save and load the AuthState as JSON (string).
So this is currently so simple that it doesn't need a specific implementation.
