### ISSUE TITLE
Which versions of OpenID are vulnerable to CVE-2007-1651 / CVE-2007-1652

### ISSUE THREAD

**Issue by alwa** [openid/AppAuth-Android#813]
Hi,
there are two CVEs (quite old) reported for OpenID:

https://www.cvedetails.com/cve/CVE-2007-1651
https://www.cvedetails.com/cve/CVE-2007-1652/

What's the status for these vulnerabilities? Are they still applicable?

The vulnerabilities were reported from https://owasp.org/www-project-dependency-check/

**Comment by agologan** [comment]
I believe the CVE is mislabeled. The issue was specific to MyOpenID provider and other providers at that time.
https://web.archive.org/web/20070429213742/http://janrain.com/blog/2007/03/22/myopenid-security-fix/

Regardless, if you believe you've found an issue with the spec please reach out to the OpenID working group and the specific provider depending on impact.
