### ISSUE TITLE
Add idp config string "client_secret"

### ISSUE THREAD

**Issue by danponce** [openid/AppAuth-Android#90]
I need to add a "client_secret" when I'm doing the token request. How can I add this?

**Comment by a0a0** [comment]
You can remove the try-catch block and use a 

`clientAuthentication = new ClientSecretPost(getString(R.string.myauth_client_secret));`

https://github.com/openid/AppAuth-Android/blob/master/app/src/net/openid/appauthdemo/TokenActivity.java#L265

**Comment by rebeckag** [comment]
Getting the client secret from a bundled string resource [is strongly discouraged](https://reviewable.io/reviews/openid/appauth-android/40#-KF8vFuplwyDSLfy4h_R) (it will lead to the client secret being distributed in plain-text with the app), compared to the dynamic registration case where it's dynamically assigned to each app instance.

@iainmcgin Maybe this should be motivated and described more clearly and added to the README?

**Comment by iainmcgin** [comment]
Agreed, we do not and will not directly support baked in client secrets in the demo app we distribute. I have a separate demo app [here](https://github.com/iainmcgin/AppAuth-Demo) which shows how you can do it, with a more thorough explanation of why doing this is generally a bad idea.

In short, don't use static client secrets in your app unless you _really_ have to.

**Comment by xperiandri** [comment]
OK, so what is the best practice for secrets? How to keep them safe in Android apps?

**Comment by iainmcgin** [comment]
Simply put, you can't. Performing a token exchange using a client secret from within your app, or in any context where you don't completely control the environment, is inherently unsafe. Don't do it.

The only exception to this is where client secrets have the same assumptions of "secrecy" that client IDs do for the IDP you are interacting with. This is generally not the case with IDPs that use client secrets - they expect them to remain secret between your organization and the IDP. Otherwise, they are pointless; they add nothing beyond the client ID itself.

The only way to keep a client ID secret is to only use them on your backend servers, where you completely control the environment in which they are used. They should never be visible to untrusted third parties, such as end user devices.

If the only way to retrieve refresh tokens from an IDP is to use client secrets, we recommend conducting the exchange with the support of your backend - use a web redirect URL that will send the authorization response to your backend, perform the exchange there, then return the tokens for forwarding to your app using a custom scheme or registered app link.

**Comment by xperiandri** [comment]
@iainmcgin, could you explain this in more detail?
I don't understand a mechanism you described.

**Comment by xperiandri** [comment]
And I don't understand the need of complicating this process for the app that I publish for my backend.
I trust my app and I can split secret into pieces, encrypt them and put into different resources of my app which will made decompilation complicated enough.
If my app secret is compromised I can delete my app definition on my backend, create new one and release new app.

Lets define the problem: user wants to be signed for long period of time without credential entering using ROPC.
What a the risks involved with client secret: with client id and client secret violator can obtain time unlimited access to users profile having refresh token.
Do I miss something?
Which options we have to keep user signed in for ROPC:
1. Save user name and password. If violator hacks device and gets them access is unlimited forever and violator can changed all confirmation data (email, phone, etc.)
2. Save client secret and exchange token. If violator hacks device he can only access data and read user profile if changing confirmation data requires password.

I would prefer second one. What about you?

**Comment by ve7jtb** [comment]
You can do the second with just the refresh token and client_id.

Without per instance dynamic client registration the client secret is theater.   Most people just grab it from the http request by using a proxy.  Hiding it in the code wont help any more than the TSA security check:)

For people doing per instance registration I can see allowing them to send the client secret.

John B.

**Comment by xperiandri** [comment]
My server ([ASOS](https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server)) does not allow issue refresh token for non-confidential apps. I suppose because of standard compliance.

So do you suggest me to add an additional method to my API which adds secret and redirects to the main method?

> For people doing per instance registration I can see allowing them to send the client secret.
I have not got what you mean.

**Comment by iainmcgin** [comment]
The primary risk involved with exposing a client secret is that it allows any other software to impersonate your app. If the user is already signed in, tokens can be easily acquired by this impersonator without consent.

For argument's sake, let's say that a shopping app is using AppAuth to authenticate using an IDP that requires a client secret. Let's also say that a malicious "coupon" app that the user installed knows about this, and has the client secret used by the shopping app. This app can query the package manager to determine if the shopping app is installed, and then attempt to trigger authorization impersonating the shopping app. This may succeed automatically, at which point the malicious app can potentially purchase items, steal credit cards etc. depending on the level access the tokens grant. Determining the client secret can even be done dynamically, as any installed Android app can read the resources of any other installed Android app (see [PackageManager.getResourcesForApplication](https://developer.android.com/reference/android/content/pm/PackageManager.html#getResourcesForApplication(java.lang.String)).

I see three possible routes forward for you:

1. Do what I suggest in an earlier comment - do the authorization from a web page you control, sending the code exchange request from your backend so that the client secret is not revealed on a channel that an attacker can easily sniff.

2. Contribute better support for non-confidential clients to ASOS:
  - Ensure it supports redirects to custom scheme URIs.
  - Add support for [PKCE](https://tools.ietf.org/html/rfc7636).
  - Ensure that authorization requests from non-confidential clients always require user interaction - don't hand out codes from the authorization flow without a user click, even if the user has previously authorized.

**Comment by iainmcgin** [comment]
>> For people doing per instance registration I can see allowing them to send the client secret.
> I have not got what you mean.

I think John was referring to [Dynamic Client Registration](https://openid.net/specs/openid-connect-registration-1_0.html), where a separate client secret is negotiated for every instance of an app. I doubt ASOS supports it.
